---
title: "The Impact of Environmental Variability on Fishers' Harvest Decisions in Chile
  using a Multi-Species Approach"
author: "Felipe J. Quezada"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    latex_engine: xelatex
    number_sections: true
bibliography: bib_paperpile.bib
csl: apa.csl # Optional: for APA-style citations
linkcolor: blue
citecolor: blue
urlcolor: blue
link-citations: TRUE 
header-includes:
  - \usepackage{setspace}
  - \onehalfspacing
  - \usepackage{indentfirst}  # Enables first-line indentation
  - \setlength{\parindent}{10pt}  # Adjusts the indentation size
---

# Introduction

The distribution and abundance of marine resources are changing in response to environmental conditions such as global ocean warming [@Poloczanska2013-qq]. Due to climate change, species distribution is expected to change in the future, reducing species availability in some areas but increasing in others. The literature that studies fishermen' responses to either changes in fish availability or policies that restrict access to fisheries [e.g., @Stafford2018-pq; @Vasquez_Caballero2023-ip] has identified that fishers can adopt the following adaptive strategies: (i) fishermen can reduce or reallocate fishing effort, either to another species or to another location [@Gonzalez-Mon2021-kj], (ii) keep following the same strategy, or, (iii) in the worst-case scenario, stop fishing entirely and find alternative employment elsewhere [@Powell2022-wj]. Among all those strategies, reallocating fishing efforts to other alternative species might be an effective adaptation strategy to climate change [@Young2018-kk]. Diversification of target species has been associated with reducing income variability [e.g., @Kasperski2013-jz; @Sethi2014-bn] and increasing resilience to both climate shock [@Cline2017-dp; @Fisher2021-lw] and interannual oceanographic variability [@Aguilera2015-wo; @Finkbeiner2015-bs].

However, switching between species requires fishers to have the skills, the gear, and the permits to do so [@Frawley2021-cw; @Powell2022-wj]. Moreover, even though a fisher may satisfy these requirements, diversification might not be possible [@Beaudreau2019-xg] as it might be constrained depending on port infrastructure, markets, and regulations [@Kasperski2013-jz; @Powell2022-wj]. Therefore, deciding which adaptation strategy to take is not straightforward and would depend on many factors. Additionally, fishers might respond differently to an analogous situation as they have different goals, skills, and preferences [@Zhang2011-wv; @Jardine2020-um; @Powell2022-wj].

In this project, we aim to answer how fishing decisions, aggregate catch levels, and the price of marine resources will be affected under different climatic scenarios in the multi-species small pelagic fishery (SPF) in Chile, composed by anchoveta (*Engraulis ringens*), jack mackerel (*Trachurus murphyi*), sardine (either *Sardinops sagax* or *Strangomera bentincki*), among others. The SPF is the most important in terms of catches in the country, accounting for almost 94% of the total Chilean catch in 2019 [@SUBPESCA2020]. By doing this research, we expect to understand better how Chilean fishers and fishing communities will adapt to climate change. To address our research question, we will estimate a multi-species harvesting model based on @Kasperski2015-jm. This model considers species' economic and biological interrelation to study the effect of climate variability on harvest decisions and substitution between species and determine the impact of different climatic scenarios on the well-being (e.g., profits) of fishers and fishing communities in Chile.

We hypothesize that if the availability of a main target species is reduced, fishers will switch to the closest substitute if the expected revenue obtained from targeting this new species is high enough to cover the expected cost. Otherwise, the vessel would decrease fishing efforts or even exit the fishery due to the lack of economically viable substitutes. Moreover, we expect that this behavior is heterogeneous depending on the geographical area of operation -- as it determines the availability of other species [@Reimer2017-jw] -- and the gear type used.

At the end of the project, I expect to find significant effects of climate variables on species stock dynamics, the cost of fishing during a trip, and the number of trips a vessel would take. The combinations of these environmental effects would be reflected in the optimal harvest level and the prices seen on the local market. I also expect to find significant interrelations between species stock and harvest, and that the composition of the catch will vary depending on the climate scenario we use for future predictions. 

Under a changing climate, studying the effect of climatic variability on fishers' harvest decisions and landings is relevant for understanding fishing communities' adaptive capacities and strategies in response to climate change, thereby enabling the design of potential mitigation measures in response to these changes. Countries have different institutions, cultures, and norms, so responses might differ depending on where the study is conducted. For this reason, conducting this research based on the Chilean fishing industry is necessary to develop local policies that aim to reduce climate change impacts on fisheries. While there is some literature on the effect of climate change on Chilean fisheries, I am unaware of local-level studies that consider a multiple-species framework and the interrelationship between the local market and fishing decisions seen under a variable climate context.^[For the case of Chile, as far as I know, the only article that study fishers' behavior using discrete choice modelling is @PeñaElNiño. This article study how El Niño Southern Oscillation (ENSO) affect fishermen location choices that participate in the Jack Mackerel fishery.]

# Methodology

To fulfill the project's objectives, and following @Kasperski2015-jm, the research entails five different stages: (i) estimating the stock dynamics of each species included in the model, (ii) estimating trip level cost functions, (iii) estimating total annual trips, (iv) estimate the inverse demand model for outputs (i.e., price responses to supply), and (v) conduct numerical optimization to examine how harvest and profits levels evolve over time. The numeral optimization uses estimated parameters from the previous four stages to conduct the optimization procedure. 

## Econometrics models


### Stock dynamics

To estimate stock dynamics, I will use annual data on stock abundance and vessel landings. This data will be obtained from stock assessment by request to the Chilean National Fisheries and Aquaculture Service (SERNAPESCA) or the Chilean Undersecretariat for Fisheries and Aquaculture (SUBPESCA). 

Following @Kasperski2015-jm, the growth of each species follows a discrete logistic function:
\begin{equation}
x_{i,y+1} + h_{iy} = \underbrace{(1 + r_i)x_{iy} + \eta_i x_{iy}^2}_{R_i(x_{iy})} + \underbrace{\sum_{j \neq i}^{n-1} a_{ij} x_{iy} x_{jy}}_{I_i(x_y)} \quad i=1,\ldots,n
\label{eq1}
\end{equation}

where $x_{iy}$ is the fish stock by species $i=1,\ldots,n$ in year $y$, $n$ is the total number of species, $h_{iy}$ is the annual harvest of species $i$ on year $y$, $r_i$ is the intrinsic growth rate of the resource $i$, $\eta_i$ is a density-dependent factor related to the carrying capacity, and $\alpha_{ij}$ are the interaction parameters between species. The system of n growth equations can be estimated simultaneously using seemingly unrelated regression (SUR) or other similar approaches. 

Following @Richter2018, we can augment \eqref{eq1} by including environmental covariates $Env_{iy}$ that affect the fish stock, such as sea surface temperature and chlorophyll levels, and an error term $\varepsilon_{iy}$ that captures random recruitment:
\begin{equation}
x_{i,y+1} + h_{iy} = \underbrace{(1 + r_i)x_{iy} + \eta_i x_{iy}^2}_{R_i(x_{iy})} + \underbrace{\sum_{j \neq i}^{n-1} a_{ij} x_{iy} x_{jy}}_{I_i(x_y)} + \rho_i Env_{iy} + \varepsilon_{iy} \quad i=1,\ldots,n
\label{eq2}
\end{equation}
where $\rho_i$ are the coefficient for the environmental covariates. The model could also be expanded to different spatial locations conditional on data availability.

### Trip level cost functions

Ignoring trip subscript, the cost functions vary by vessel $v=1,\ldots,V_g$ and gear used $g=1,\ldots,G$, where $V_g$ is the number of observations using gear type $g$, and $G$ is the total number of available (or observed) gears: 
\begin{equation}
C_{vg} = \sum_{i=1}^{2n+M+k} \alpha_{g, \mathbf{X}_i} \mathbf{X}_{ivg} + \frac{1}{2} \sum_{i=1}^{2n+M+k} \sum_{j=1}^{2n+M+k} \alpha_{g, \mathbf{X}_i\mathbf{X}_j} \mathbf{X}_{ivg} \mathbf{X}_{jvg}
\label{eq3}
\end{equation}
where $C_{vg}= w z_{vg}^*$, $\mathbf{X}_{vg}=[w;h_{vg};x;Z_v]$, $w$ is a $V_g \times M$ matrix of variable input prices, $h_{vg}$ is an $V_g \times n$ matrix of harvest quantities and $Z_v$ is a vector of fixed vessel characteristics for vessel v, x is an V_g×n matrix of given stock levels of the species of interest, and $Z_v$ is an $V_g \times k$ matrix of given vessel characteristics. Therefore, $\mathbf{X}_{vg}$ is a $V_g \times (2n+M+k)$ matrix, and $\mathbf{X}_{ivg}$ represents the *i*th column of the $\mathbf{X}_{vg}$ matrix.

Together with estimating the restricted cost function, we estimate the conditional input demand equations. This addition allows an increase in the degrees of freedom by imposing cross-equation parameter constraints and allows for the testing of, for instance, jointness in inputs [@Kasperski2015-jm]. The conditional input demand equations are derived by Shepard's Lemma:
\begin{equation}
\frac{\partial C_{vg}}{\partial w_m} = z^*_{vg,w_m} = \alpha_{g,w_m} + \sum_{j=1}^{2n+M+k} \alpha_{g,w_m,\mathbf{X}_j} \mathbf{X}_{jvg} \quad m=1,\ldots,M.
\label{eq4}
\end{equation}

Similar to stock dynamics, the system of equations formed by \eqref{eq3} and \eqref{eq4} can be estimated using SUR. To comply with economic theory, and to reduce even more the number of parameters to estimate, the following restrictions are imposed when estimating \eqref{eq4}:

1. Symmetry of the cost function, where
  \begin{equation}
  \alpha_{g,\mathbf{X}_i\mathbf{X}_j} = \alpha_{g,\mathbf{X}_j\mathbf{X}_i} \quad \forall \quad i=1,\ldots,(2n + M + k); \ i \neq j; \ g = 1,\ldots, G.
  \end{equation}

2. Linear homogeneity in input prices, where
  \begin{equation}
  \sum_m^M \alpha_{g,w_m} = 1 \ \text{and} \ \sum_m^M \alpha_{g,w_m,\mathbf{X}_i} = 0 \quad i=1,\ldots,(2n + M + k); \ g = 1,\ldots, G.
  \end{equation}

Data at the trip level is available upon request from the Chilean Fisheries Research Institute (IFOP), which registers geo-referenced catch information on the Chilean fleet's fishing operation per trip [see e.g. @PeñaElNiño and [IFOP data observatory](ifop.dataobservatory.net)]. As inputs we can use the time spent at sea during a trip, where the price is the average wage pay to crew member per hour, and the distance traveled during a trip, where the price of distance traveled is the diesel cost.

To link this function to climate change, we can also include additional environmental variables $Env$ to $\mathbf{X}_{vg}$ such as wind intensity and wave conditions in each trip at the harvest location, upon data availability. Therefore, the augmented $X_{vg}$ matrix becomes $\mathbf{X}^{'}_{vg} = [w;h_{vg};x;Z_v;Env]$.

### Total annual trips

The number of trips a vessel will take in a given year for each gear type used is assumed to follow a Poison distribution [@Kasperski2015-jm]:

\begin{equation}
Pr\left[T^*_{vgy} = t_v \right]=\frac{exp^{exp(U'_vg\beta_g)}exp(U'_{vg}\beta_g)^{t_v}}{t_v !}
\end{equation}

### Inverse demand model for outputs



## Numerical optimization

## Potential extension of the project

# Results

# Discussion

## Potential extension of the project

Several other extensions to the model can be incorporated to be improved. For instance, the geographical space where fishermen operate is relevant, as depending on the location chosen and when to participate, the set of potential choices would vary (Reimer et al. 2017). As I mentioned above, it is possible to extend the stock dynamic model by considering different locations. The model would also require that the participation decision, which is captured by the Poisson model on the annual number of trips, should then consider the decision to participate in a determined fishing ground, connecting the multi-species model of @Kasperski2015-jm to the literature of location choice modeling (e.g., Dupont 1993; Smith 2005; Hicks et al. 2020). Regarding the determination of prices, the model assumes that quantities are exogenous because the quota is likely to be binding. However, we can relax this assumption by considering that all variables in the inverse demand equations are endogenous by estimating a vector autoregressive (VAR) model (Juselius 2006). In other words, harvest $h_{vg}$ has its own equations in the system. 

# Conclusions

# Repository

The source code for this project is available on [GitHub](https://github.com/fquezadae/Impact-of-Environmental-Variability-on-Harvest)


# References